const { SlashCommandBuilder } = require('discord.js');
const { EmbedBuilder } = require('discord.js');
const Schema = require('../models/allJournalEntries');
const request = require('request');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('quote')
        .setDescription('Get a random Stoic quote!'),
    async execute(interaction) {
        const apiURL = 'https://stoic-server.herokuapp.com/random';

        request({ 'url': apiURL, 'json': true }, function (error, response, body) {
            const quote = body[0]['body'];
            const author = body[0]['author'];
            const quoteSource = body[0]['quotesource'];

            const quoteEmbed = new EmbedBuilder()
                .setColor(0xffd700)
                .setDescription(quote)
                .setTitle('Quote')
                .addFields(
                    { name: '\u200B', value: '\u200B' },
                    { name: 'Source', value: quoteSource },
                    { name: 'Author', value: author },
                )
                .setTimestamp()
                .setFooter({ text: 'Generated by The Stoic Mentor', iconURL: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/0_S%C3%A9n%C3%A8que_-_Mus%C3%A9e_du_Prado_-_Cat._144_-_%282%29.JPG/240px-0_S%C3%A9n%C3%A8que_-_Mus%C3%A9e_du_Prado_-_Cat._144_-_%282%29.JPG' })
            //interaction.reply({ content: quote + '\n\n- ' + author + '\n\n(' + quoteSource + ')', ephemeral: false });
            interaction.reply({ embeds: [quoteEmbed] });
        });
    },
};